export const states = {
	'Vinnytsia oblast': 'Вінницька область',
	'Volyn oblast': 'Волинська область',
	'Dnipropetrovsk oblast': 'Дніпропетровська область',
	'Donetsk oblast': 'Донецька область',
	'Zhytomyr oblast': 'Житомирська область',
	'Zakarpattia oblast': 'Закарпатська область',
	'Zaporizhzhia oblast': 'Запорізька область',
	'Ivano-Frankivsk oblast': 'Івано-Франківська область',
	'Kyiv oblast': 'Київська область',
	'Kirovohrad oblast': 'Кіровоградська область',
	'Luhansk oblast': 'Луганська область',
	'Lviv oblast': 'Львівська область',
	'Mykolaiv oblast': 'Миколаївська область',
	'Odesa oblast': 'Одеська область',
	'Poltava oblast': 'Полтавська область',
	'Rivne oblast': 'Рівненська область',
	'Sumy oblast': 'Сумська область',
	'Ternopil oblast': 'Тернопільська область',
	'Kharkiv oblast': 'Харківська область',
	'Kherson oblast': 'Херсонська область',
	'Khmelnytskyi oblast': 'Хмельницька область',
	'Cherkasy oblast': 'Черкаська область',
	'Chernivtsi oblast': 'Чернівецька область',
	'Chernihiv oblast': 'Чернігівська область',
	Kyiv: 'м. Київ',
};
