export type ConvertOptions = {
  from: Currency;
  to: Currency;
  amount: number;
};

export type ConvertResponse = {
  baseCurrency: {
    code: Currency;
    name: string;
    amount: string;
  };
  rateCurrency: {
    code: Currency;
    name: string;
    amount: string;
  };
  updatedDate: Date;
};

export enum Currency {
  'US Dollar' = 'USD',
  'Euro' = 'EUR',
  'British Pound' = 'GBP',
  'Canadian Dollar' = 'CAD',
  'Australian Dollar' = 'AUD',
  'Japanese Yen' = 'JPY',
  'Cardano' = 'ADA',
  'Emirati Dirham' = 'AED',
  'Afghan Afghani' = 'AFN',
  'Albanian Lek' = 'ALL',
  'Armenian Dram' = 'AMD',
  'Dutch Guilder' = 'ANG',
  'Angolan Kwanza' = 'AOA',
  'Argentine Peso' = 'ARS',
  'Aruban or Dutch Guilder' = 'AWG',
  'Azerbaijan Manat' = 'AZN',
  'Bosnian Convertible Mark' = 'BAM',
  'Barbadian or Bajan Dollar' = 'BBD',
  'Bitcoin Cash' = 'BCH',
  'Bangladeshi Taka' = 'BDT',
  'Bulgarian Lev' = 'BGN',
  'Bahraini Dinar' = 'BHD',
  'Burundian Franc' = 'BIF',
  'Bermudian Dollar' = 'BMD',
  'Bruneian Dollar' = 'BND',
  'Bolivian Bolíviano' = 'BOB',
  'Brazilian Real' = 'BRL',
  'Bahamian Dollar' = 'BSD',
  'Bitcoin' = 'BTC',
  'Bhutanese Ngultrum' = 'BTN',
  'Botswana Pula' = 'BWP',
  'Belarusian Ruble' = 'BYR',
  'Belizean Dollar' = 'BZD',
  'Congolese Franc' = 'CDF',
  'Swiss Franc' = 'CHF',
  'Chilean Peso' = 'CLP',
  'Chinese Yuan Renminbi' = 'CNY',
  'Colombian Peso' = 'COP',
  'Costa Rican Colon' = 'CRC',
  'Cuban Convertible Peso' = 'CUC',
  'Cuban Peso' = 'CUP',
  'Cape Verdean Escudo' = 'CVE',
  'Czech Koruna' = 'CZK',
  'Djiboutian Franc' = 'DJF',
  'Danish Krone' = 'DKK',
  'Dogecoin' = 'DOGE',
  'Dominican Peso' = 'DOP',
  'Polkadot' = 'DOT',
  'Algerian Dinar' = 'DZD',
  'Estonian Kroon' = 'EEK',
  'Egyptian Pound' = 'EGP',
  'Eritrean Nakfa' = 'ERN',
  'Ethiopian Birr' = 'ETB',
  'Ethereum' = 'ETH',
  'Fijian Dollar' = 'FJD',
  'Falkland Island Pound' = 'FKP',
  'Georgian Lari' = 'GEL',
  'Guernsey Pound' = 'GGP',
  'Ghanaian Cedi' = 'GHS',
  'Gibraltar Pound' = 'GIP',
  'Gambian Dalasi' = 'GMD',
  'Guinean Franc' = 'GNF',
  'Guatemalan Quetzal' = 'GTQ',
  'Guyanese Dollar' = 'GYD',
  'Hong Kong Dollar' = 'HKD',
  'Honduran Lempira' = 'HNL',
  'Croatian Kuna' = 'HRK',
  'Haitian Gourde' = 'HTG',
  'Hungarian Forint' = 'HUF',
  'Indonesian Rupiah' = 'IDR',
  'Israeli Shekel' = 'ILS',
  'Isle of Man Pound' = 'IMP',
  'Indian Rupee' = 'INR',
  'Iraqi Dinar' = 'IQD',
  'Iranian Rial' = 'IRR',
  'Icelandic Krona' = 'ISK',
  'Jersey Pound' = 'JEP',
  'Jamaican Dollar' = 'JMD',
  'Jordanian Dinar' = 'JOD',
  'Kenyan Shilling' = 'KES',
  'Kyrgyzstani Som' = 'KGS',
  'Cambodian Riel' = 'KHR',
  'Comorian Franc' = 'KMF',
  'North Korean Won' = 'KPW',
  'South Korean Won' = 'KRW',
  'Kuwaiti Dinar' = 'KWD',
  'Caymanian Dollar' = 'KYD',
  'Kazakhstani Tenge' = 'KZT',
  'Lao Kip' = 'LAK',
  'Lebanese Pound' = 'LBP',
  'Chainlink' = 'LINK',
  'Sri Lankan Rupee' = 'LKR',
  'Liberian Dollar' = 'LRD',
  'Basotho Loti' = 'LSL',
  'Litecoin' = 'LTC',
  'Lithuanian Litas' = 'LTL',
  'Terra' = 'LUNA',
  'Latvian Lat' = 'LVL',
  'Libyan Dinar' = 'LYD',
  'Moroccan Dirham' = 'MAD',
  'Moldovan Leu' = 'MDL',
  'Malagasy Ariary' = 'MGA',
  'Macedonian Denar' = 'MKD',
  'Burmese Kyat' = 'MMK',
  'Mongolian Tughrik' = 'MNT',
  'Macau Pataca' = 'MOP',
  'Mauritanian Ouguiya' = 'MRU',
  'Mauritian Rupee' = 'MUR',
  'Maldivian Rufiyaa' = 'MVR',
  'Malawian Kwacha' = 'MWK',
  'Mexican Peso' = 'MXN',
  'Malaysian Ringgit' = 'MYR',
  'Mozambican Metical' = 'MZN',
  'Namibian Dollar' = 'NAD',
  'Nigerian Naira' = 'NGN',
  'Nicaraguan Cordoba' = 'NIO',
  'Norwegian Krone' = 'NOK',
  'Nepalese Rupee' = 'NPR',
  'New Zealand Dollar' = 'NZD',
  'Omani Rial' = 'OMR',
  'Panamanian Balboa' = 'PAB',
  'Peruvian Sol' = 'PEN',
  'Papua New Guinean Kina' = 'PGK',
  'Philippine Peso' = 'PHP',
  'Pakistani Rupee' = 'PKR',
  'Polish Zloty' = 'PLN',
  'Paraguayan Guarani' = 'PYG',
  'Qatari Riyal' = 'QAR',
  'Romanian Leu' = 'RON',
  'Serbian Dinar' = 'RSD',
  'Russian Ruble' = 'RUB',
  'Rwandan Franc' = 'RWF',
  'Saudi Arabian Riyal' = 'SAR',
  'Solomon Islander Dollar' = 'SBD',
  'Seychellois Rupee' = 'SCR',
  'Sudanese Pound' = 'SDG',
  'Swedish Krona' = 'SEK',
  'Singapore Dollar' = 'SGD',
  'Saint Helenian Pound' = 'SHP',
  'Sierra Leonean Leone' = 'SLL',
  'Somali Shilling' = 'SOS',
  'Seborgan Luigino' = 'SPL',
  'Surinamese Dollar' = 'SRD',
  'Sao Tomean Dobra' = 'STN',
  'Salvadoran Colon' = 'SVC',
  'Syrian Pound' = 'SYP',
  'Swazi Lilangeni' = 'SZL',
  'Thai Baht' = 'THB',
  'Tajikistani Somoni' = 'TJS',
  'Turkmenistani Manat' = 'TMT',
  'Tunisian Dinar' = 'TND',
  "Tongan Pa'anga" = 'TOP',
  'Turkish Lira' = 'TRY',
  'Trinidadian Dollar' = 'TTD',
  'Tuvaluan Dollar' = 'TVD',
  'Taiwan New Dollar' = 'TWD',
  'Tanzanian Shilling' = 'TZS',
  'Ukrainian Hryvnia' = 'UAH',
  'Ugandan Shilling' = 'UGX',
  'Uniswap' = 'UNI',
  'Uruguayan Peso' = 'UYU',
  'Uzbekistani Som' = 'UZS',
  'Venezuelan Bolívar' = 'VES',
  'Vietnamese Dong' = 'VND',
  'Ni' = 'VUV',
  'Samoan Tala' = 'WST',
  'Central African CFA Franc BEAC' = 'XAF',
  'Silver Ounce' = 'XAG',
  'Gold Ounce' = 'XAU',
  'East Caribbean Dollar' = 'XCD',
  'IMF Special Drawing Rights' = 'XDR',
  'Stellar Lumen' = 'XLM',
  'CFA Franc' = 'XOF',
  'Palladium Ounce' = 'XPD',
  'CFP Franc' = 'XPF',
  'Platinum Ounce' = 'XPT',
  'Ripple' = 'XRP',
  'Yemeni Rial' = 'YER',
  'South African Rand' = 'ZAR',
  'Zambian Kwacha' = 'ZMW',
  'Zimbabwean Dollar' = 'ZWD',
}
